import sqlite3
import pandas as pd
import time
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players # Needed to look up ID by name

DB_PATH = '/home/TheEdgeBoard/EdgeBoard/edgeboard.db'

def sync_stats():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # --- 1. SAFEGUARD: Add missing columns if they don't exist yet ---
    try:
        cursor.execute("ALTER TABLE active_lines ADD COLUMN trend_history TEXT")
    except sqlite3.OperationalError:
        pass # Column already exists
        
    try:
        cursor.execute("ALTER TABLE active_lines ADD COLUMN last_game_hit INTEGER")
    except sqlite3.OperationalError:
        pass

    print("Fetching active prospects...")
    # --- 2. MATCH YOUR DB: Use active_lines and line_value ---
    prospects = cursor.execute("SELECT * FROM active_lines WHERE line_value IS NOT NULL").fetchall()
    
    updates = []
    
    for p in prospects:
        try:
            player_name = p['player_name']
            
            # --- 3. LOOKUP PLAYER ID ---
            # We must find the NBA API ID using the player's name
            player_dict = players.find_players_by_full_name(player_name)
            if not player_dict:
                print(f"Player ID not found for {player_name}")
                continue
            pid = player_dict[0]['id']
            
            # Fetch last 20 games (Removing 'season' lets it default to the current active season)
            time.sleep(0.6) # Prevent rate-limiting
            log = playergamelog.PlayerGameLog(player_id=pid).get_data_frames()[0].head(20)
            
            prop = p['prop_type']
            line = float(p['line_value'])
            
            # --- 4. CORRECT PROP MAPPING ---
            # Match the abbreviations generated by sync_odds.py
            col = None
            if prop in ['PTS', 'REB', 'AST', 'FG3M']:
                col = prop
            elif prop == 'PRA':
                log['PRA'] = log['PTS'] + log['REB'] + log['AST']
                col = 'PRA'
            elif prop == 'PR':
                log['PR'] = log['PTS'] + log['REB']
                col = 'PR'
            elif prop == 'RA':
                log['RA'] = log['REB'] + log['AST']
                col = 'RA'
                
            if col and not log.empty:
                # Calculate Hit History (1 = Covered Line, 0 = Missed)
                hits = ['1' if val > line else '0' for val in log[col]]
                trend_str = ",".join(hits)
                last_hit = int(hits[0]) if hits else 0
                
                updates.append((trend_str, last_hit, player_name, prop))
                print(f"Updated {player_name}: Last Hit={last_hit}, Trend={trend_str[:5]}...")
                
        except Exception as e:
            print(f"Skipping {p['player_name']}: {e}")

    # --- 5. UPDATE YOUR DB ---
    if updates:
        cursor.executemany('UPDATE active_lines SET trend_history = ?, last_game_hit = ? WHERE player_name = ? AND prop_type = ?', updates)
        conn.commit()
        print(f"Successfully updated stats for {len(updates)} props.")
    else:
        print("No stats to update.")
        
    conn.close()

if __name__ == "__main__":
    sync_stats()